version: "3"
services:
  pub:
    build:
      context: .
      dockerfile: ./pub/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./pub:/go/src
    tty: true
    links:
      - "redis:redis"
    depends_on:
      - redis
  sub:
    build:
      context: .
      dockerfile: ./sub/Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./sub:/go/src
    tty: true
    links:
      - "redis:redis"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - "./data/redis:/data"
