version: "3"
services:
  pub:
    build:
      context: .
      dockerfile: ./pub/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./pub:/go/src
    tty: true
    depends_on:
      - redis
  sub1:
    build:
      context: .
      dockerfile: ./sub/Dockerfile
    ports:
      - "8091:8080"
    volumes:
      - ./sub:/go/src
    tty: true
    depends_on:
      - redis
  sub2:
    build:
      context: .
      dockerfile: ./sub/Dockerfile
    ports:
      - "8092:8080"
    volumes:
      - ./sub:/go/src
    tty: true
    depends_on:
      - redis
  sub3:
    build:
      context: .
      dockerfile: ./sub/Dockerfile
    ports:
      - "8093:8080"
    volumes:
      - ./sub:/go/src
    tty: true
    depends_on:
      - redis
  redis:
    image: "redis:7.0"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - "./data/redis:/data"
